package com.videostreaming.notification.model;

public enum NotificationType {
    WELCOME,
    SYSTEM,
    MESSAGE_RECEIVED,
    REVIEW_RECEIVED,
    REVIEW_REPLY,
    CERTIFICATE_ISSUED,
    COURSE_ENROLLED,
    COURSE_COMPLETED,
    ASSIGNMENT_GRADED,
    ASSIGNMENT_SUBMITTED,
    DISCUSSION_REPLY,
    QUIZ_RESULT,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    CLASS_BOOKED,
    CLASS_CANCELLED,
    WAITLIST_PROMOTED,
    CLASS_REMINDER,
    PAYMENT_RELEASED,
    PAYOUT_COMPLETED,
    LIVE_SESSION_SCHEDULED,
    LIVE_SESSION_STARTING,
    NEW_STUDENT_ENROLLED
}
